### PR TITLE
Create classes for TDK config sections so they are grouped in inspector

### PR DESCRIPTION
**Pull request by lefarchi**
image

### CODE REVIEW

**Comment by alecananian** [comment]
@lefarchi thoughts on breaking out the "general" configs so they're not nested? Does it look too crowded with them at the top level?

**Comment by lefarchi** [comment]
image
Here is how it would look. I like being able to collapse the api keys/urls/ids it but either way its fine for me, perhaps its clearer to have them unnested

**Review by alecananian — APPROVED** [review]
Nested one is cleaner, thanks!

**Comment by lefarchi** [comment]
sounds good! feel free to merge it whenever

**Pull request merged**
